language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

stages:
    - linting
    - test

jobs:
  include:
    - stage: linting
      env:
        - LINT_CHECK="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="sale_invoice_policy"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="sale_invoice_policy"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="sale_invoice_policy" MAKEPOT="1"
    - stage: test
      env:
        - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="sale_invoice_policy" MAKEPOT="1"

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0" WKHTMLTOPDF_VERSION="0.12.4"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
