name: tests

on:
  pull_request:
    branches:
      - "10.0*"
  push:
    branches:
      - "10.0"
      - "10.0-ocabot-*"

jobs:
  unreleased-deps:
    runs-on: ubuntu-latest
    name: Detect unreleased dependencies
    steps:
      - uses: actions/checkout@v2
      - run: |
          for reqfile in requirements.txt test-requirements.txt ; do
              if [ -f ${reqfile} ] ; then
                  result=0
                  # reject non-comment lines that contain a / (i.e. URLs, relative paths)
                  grep "^[^#].*/" ${reqfile} || result=$?
                  if [ $result -eq 0 ] ; then
                      echo "Unreleased dependencies found in ${reqfile}."
                      exit 1
                  fi
              fi
          done
  test:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_procurement_group_by_requested_date_sale_sourced_by_line"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_procurement_group_by_requested_date_sale_sourced_by_line"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_procurement_group_by_requested_date"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_procurement_group_by_requested_date"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_delivery_split_date"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_delivery_split_date"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_stock_picking_blocking_proc_group_by_line"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_stock_picking_blocking_proc_group_by_line"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_sourced_by_line"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_sourced_by_line"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_procurement_group_by_line"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_procurement_group_by_line"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_order_action_invoice_create_hook"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_order_action_invoice_create_hook"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_invoice_group_method"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_invoice_group_method"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_merge_draft_invoice"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_merge_draft_invoice"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_promotion_rule"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_promotion_rule"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_promotion_rule_delivery"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_promotion_rule_delivery"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            include: "sale_promotion_rule_assortment"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            include: "sale_promotion_rule_assortment"
            name: test with OCB
          - container: ghcr.io/oca/oca-ci/py2.7-odoo10.0:latest
            exclude: "sale_procurement_group_by_requested_date_sale_sourced_by_line,sale_procurement_group_by_requested_date,sale_delivery_split_date,sale_stock_picking_blocking_proc_group_by_line,sale_sourced_by_line,sale_procurement_group_by_line,sale_order_action_invoice_create_hook,sale_invoice_group_method,sale_merge_draft_invoice,sale_promotion_rule,sale_promotion_rule_delivery,sale_promotion_rule_assortment"
            makepot: "true"
            name: test with Odoo
          - container: ghcr.io/oca/oca-ci/py2.7-ocb10.0:latest
            exclude: "sale_procurement_group_by_requested_date_sale_sourced_by_line,sale_procurement_group_by_requested_date,sale_delivery_split_date,sale_stock_picking_blocking_proc_group_by_line,sale_sourced_by_line,sale_procurement_group_by_line,sale_order_action_invoice_create_hook,sale_invoice_group_method,sale_merge_draft_invoice,sale_promotion_rule,sale_promotion_rule_delivery,sale_promotion_rule_assortment"
            name: test with OCB
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    env:
      INCLUDE: "${{ matrix.include }}"
      EXCLUDE: "${{ matrix.exclude }}"
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install addons and dependencies
        run: oca_install_addons
      - name: Check licenses
        run: manifestoo -d . check-licenses
      - name: Check development status
        run: manifestoo -d . check-dev-status --default-dev-status=Beta
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
      - uses: codecov/codecov-action@v1
      - name: Update .pot files
        run: oca_export_and_push_pot https://x-access-token:${{ secrets.GIT_PUSH_TOKEN }}@github.com/${{ github.repository }}
        if: ${{ matrix.makepot == 'true' && github.event_name == 'push' && github.repository_owner == 'OCA' }}
